### ISSUE TITLE
Document goroutine safety of Localizer

### ISSUE THREAD

**Issue by velomarc** [nicksnyder/go-i18n#105]
is  Localizer thread/goroutine safe ?

**Comment by nicksnyder** [comment]
Localizer itself is goroutine safe. It merely reads data from the bundle.

It would *not* be goroutine safe to modify the bundle (e.g. add translations) concurrently with using that bundle in a Localizer.

I anticipate that most applications will load all the translations in a bundle on startup (e.g. `init()`) before they start passing the bundle to localizers. If that is not the case for your application then you may need to add some mutexes to your application logic. If this turns out to be a common case, then I am open to handling this in the library (e.g. adding a `SynchronizedBundle` type which manages a mutex).

**Comment by velomarc** [comment]
Got it, thank you
