### ISSUE TITLE
I can't create translate files by command "goi18n merge"

### ISSUE THREAD

**Issue by cye1024** [nicksnyder/go-i18n#110]
Hi 
  I created file "active.en.toml" by `goi18n edtract`, but it happened nothing while use `goi18n merge active.en.toml`, please tell me what's the wrong I did. thanks.

**Comment by thuandoan274** [comment]
Me too, I don't know how to use goi18n merge hay extract

**Comment by nicksnyder** [comment]
What were you expecting `goi18n merge` to do?

You can run `goi18n extract --help` and `goi18n merge --help` for more info.

**Comment by nicksnyder** [comment]
> which shows me the missing translations.

There are no missing translations in your example. You have a single translation and it is already translated.

**Comment by petergtz** [comment]
@nicksnyder I guess I'm misunderstanding the commands. Maybe you can point out where I'm wrong in my thinking when I explain how I thought the workflow works:

Let's say I have a `main.go` with some
```go
localizer.MustLocalize(&i18n.LocalizeConfig{DefaultMessage: &i18n.Message{
    ID:    "Hello",
    Other: "Hallo",
}})
```

First, I run `goi18n extract -sourceLanguage de`. That creates a `active.de.toml` with content:
```toml
Hello = "Hallo"
```

Next, I create an empty file `active.en.toml` and run `goi18n merge active.en.toml`

In `active.en.toml` I would expect something like:
```toml
Hello = ""
```

So that now I could fill in the blanks. But this is not happening. In fact, nothing changes after that last call to `goi18n`.

Where's the flaw in my understanding?

**Comment by nicksnyder** [comment]
Sorry for the delay in responding here!

> Next, I create an empty file `active.en.toml` and run `goi18n merge active.en.toml`

goi18n doesn't know what messages are missing unless you give it all messages and the source language again. Your merge command should look like this:

```
goi18n merge -sourceLanguage de active.de.toml active.en.toml
```

This will generate `translate.en.toml` with the messages that need to be translated from German to English. No `active.en.toml` will be generated because you don't have any translations for English yet. When it is translated, you can just rename `translate.en.toml` to `active.en.toml` and load it into your bundle at runtime.

I have updated the documentation in the readme to hopefully make this clearer (https://github.com/nicksnyder/go-i18n/pull/140).

I hope this answers your question! I am going to close this but feel free to re-open or file more issues if you have more questions.
