### ISSUE TITLE
Why double specify the format with goi18n merge

### ISSUE THREAD

**Issue by hanzei** [nicksnyder/go-i18n#161]
When running `goi18n merge` with a different format then toml you have to specify the format via the filename **and** via the filename.

E.g. after doing the translations you have to run
`goi18n merge -format json active.*.json translate.*.json`

For signification I think you can assume:
1. `active` and `translate` use the same format
2. `*.json` file only contain `json` formatted data

Let me know what you think about this.

**Comment by nicksnyder** [comment]
> `*.json` file only contain `json` formatted data

This is already the case. Input files are parsed according to their suffix (e.g. files that have the `.json` extension are parsed as JSON).

> `active` and `translate` use the same format

While it is certainly unlikely that users will mix formats, but I don't see a benefit to making the assumption. We can easily parse each file according to its extension, which means that the following is valid:
`goi18n merge -format json active.*.json translate.*.toml`

The `-format` flag just specifies the output format.

It would be possible to improve the default behavior so that passing the `-format` flag is not necessary if all input files contain the same extension. Or it could default to the format of the first input file. 

Which of these options sound best to you? Are you willing to open a PR? Relevant code is around here:
https://sourcegraph.com/github.com/nicksnyder/go-i18n/-/blob/v2/goi18n/merge_command.go#L71:16

**Comment by hanzei** [comment]
Sorry for the late response.

> While it is certainly unlikely that users will mix formats, but I don't see a benefit to making the assumption. We can easily parse each file according to its extension, which means that the following is valid:
> `goi18n merge -format json active.*.json translate.*.toml`
> 
> The `-format` flag just specifies the output format.
> 

This example is the use case I'm questioning. Why would you save `json` data in a file names `.toml`? Or do I misunderstand the behaviour?

**Comment by nicksnyder** [comment]
> Why would you save json data in a file names .toml?

You wouldn’t. The name of the output file is determined by the format used. If `-format toml` then the file names will have the `.toml` suffix.

**Comment by hanzei** [comment]
> You wouldn’t. The name of the output file is determined by the format used. If -format toml then the file names will have the .toml suffix.

But why do you need to specify the target file anyway? Why isn't `goi18n merge -format toml translate.*.toml` enough?

**Comment by nicksnyder** [comment]
I am not sure where the misunderstanding is here.

All the files you list are input files. They will be parsed according to their file extension, so you can mix and match different input files with different formats (although this probably never happens in practice). In the end, go-i18n will write and output file.

The `format` flag tells go-i18n the format to use when writing the output file. The output file will have an extension that matches the format used.


> goi18n merge -format toml translate.*.toml

go-i18n does not make any assumptions about what files you want to merge translations into, you need to pass go-i18n all the files you want to merge together.
