### ISSUE TITLE
Is "Localizer" thread safe?

### ISSUE THREAD

**Issue by recklessMo** [nicksnyder/go-i18n#188]
Create a Localizer to use for a set of language preferences.

func(w http.ResponseWriter, r *http.Request) {
    lang := r.FormValue("lang")
    accept := r.Header.Get("Accept-Language")
    localizer := i18n.NewLocalizer(bundle, lang, accept)
}

I am wondering if I can create one global localizer object and reuse it among multiple goroutines?

**Comment by nicksnyder** [comment]
Localizer is goroutine safe; however, Bundle is not, which means that all translations must be added to your Bundle before creating any Localizers.

**Comment by saintAsmita** [comment]
could I create a map of Localizers when application starting.  When process each request, get a localizer from the map ?

**Comment by begetan** [comment]
@saintAsmita looks like it is working solution

**Comment by nicksnyder** [comment]
> could I create a map of Localizers when application starting. When process each request, get a localizer from the map ?

If you have a finite set of strings you pass for the 2+ arguments to `NewLocalizer` then yes (this is possible if you have a language selector dropdown on your site, or if it is controlled by a finite set of subdomains), but if you are localizing based on User-Agent header from the user, then this won't work because you can't precompute all possible User-Agent values.

**Comment by zaddok** [comment]
@nicksnyder I feel like this should be mentioned in the documentation somewhere.

`Localizer is goroutine safe; however, Bundle is not, which means that all translations must be added to your Bundle before creating any Localizers.`

It feels like this is a common use case, and your answer is clear and perfect. Thanks.
