### ISSUE TITLE
Understanding the complexity of this lib

### ISSUE THREAD

**Issue by fgagneten** [nicksnyder/go-i18n#203]
Hi guys!

I was looking for a i18n to use in my Go Project. I come from Javascript using i18n.

I can't understand the complexity of this lib. I mean, I have to write too much code just to translate a phrase .

Is there a way to just translate (without placeholder) a simple word using something like this?:
    hello := $i18n.Message("Hello")

Which is the shortest way to translate a word without placeholder just a sentence like "Hello, How are you?

Thanks

**Comment by kataras** [comment]
Hello @fgagneten,

I am not used to dive into like this way but this issue is **25 days old** and nobody got the time to answer you, **as an open-source contributor, I feel compelled to say sorry about it**. I am not the author or a contributor of this library but I am the author of [Iris web framework](https://github.com/kataras/iris) - it's one of the few open-source projects hosted at GitHub which its users get answers at the same day.

Let me help you, if you use a web framework, then you should check if it does support an `i18n` middleware (most of the times it's much simpler than go-i81n which is designed for larger applications). 

For example, if you use Iris you can **get all go-i18n features but simpler as it provides a middleware for it.**

**./locales/en-US.all.yaml**
```ini
- id: hi
  translation: "hi {{.}}"
```

**a .go file**

```go
app := iris.New()
locale := i18n.New(
	"./locales/en-US.all.yaml",
	"./locales/en-US.errors.yaml",
	"./locales/zh-CN.all.yaml",
)

app.Use(locale.Serve)

// Route, use of i18n in a line of `.Translate("key", optionalArguments)`.
app.Get("/", func(ctx iris.Context){
    message := ctx.Translate("hi", "iris")
    ctx.Writef("translated: %s", message )
})
```

Inside templates you can bind the `ctx.Translate` method itself.

```go
app.Get("/templates", func(ctx iris.Context) {
	ctx.View("index.html", iris.Map{
		"tr": ctx.Translate,
	})
	// it will return "hello, iris"
	// when {{call .tr "hi" "iris"}}
})
```

```html
{{call .tr "hi" "iris"}}
```

> The full example's source code is located at: [iris-contrib/middleare/go-i18n](https://github.com/iris-contrib/middleware/tree/master/go-i18n/_example).

Iris web framework has a builtin, `i18n` middleware as well, (works with **.ini files and it is much more simpler and a bit faster** `hi = hi, %s` and `ctx.Translate("hi", "iris")` ), so if you still not comfortable with `go-i18n` you can visit our [_examples/miscellaneous/i18n](https://github.com/kataras/iris/tree/master/_examples/miscellaneous/i18n) to learn more about it, I am sure you'll appreciate the simplicity of it.

Thanks,
Hope you the bests, tell us if my comment helped you out!

**Comment by nicksnyder** [comment]
> Is there a way to just translate (without placeholder) a simple word using something like this?:
hello := $i18n.Message("Hello")

```go
localizer.LocalizeMessage(&i18n.Message{Other: "Hello"})
```

It might be nice to add a `LocalizeString` method to `Localizer` that does this. (e.g. localizer.LocalizeString("Hello")`). Want to open a PR?

> I can't understand the complexity of this lib. I mean, I have to write too much code just to translate a phrase .

What do you consider to be too much code? Here is some background on why the various APIs exist:

Bundles store the translations that are available to your application. Without bundles, this data would need to be stored in global state, which causes issues with concurrency and makes it harder to test.

Localizers capture the preferred language to use based on available translations and the user's preferences. Without Localizers, this expensive computation would need to be repeated for each translation lookup.

Finally, the Localize method (and its variants) allow you to lookup a single translation. It is structured so that it correctly handles pluralization across all languages, supports data templating, and supports extracting translation files directly from source code so that it easy to get the messages from your app translated.
