### ISSUE TITLE
Adding a "zero" plural form?

### ISSUE THREAD

**Issue by cyChop** [nicksnyder/go-i18n#232]
The One/Other feature is neat!

Yet, I often find myself limitated because I need a specific case for the zero value. Would it be relevant to integrate it as a feature in go-i18n? That would be much better than a separate if/else in code.

(Disclosure: I use go-i18n through Hugo's i18n feature.)

**Comment by nicksnyder** [comment]
First, there is a [zero](https://sourcegraph.com/github.com/nicksnyder/go-i18n/-/blob/v2/i18n/message.go#L28:2) category, but it probably isn't what you are looking for because the `zero` category doesn't necessarily mean the number `0` in all languages. Even in English, there is only `One` and `Other` (English treats 0 as "other" and does not have a special pluralization for it).

If you need specific behavior for the number `0`, then you need to write application logic.

Here are previous discussions:
https://github.com/gohugoio/hugo/issues/5164#issuecomment-418774513
https://github.com/nicksnyder/go-i18n/issues/112#issuecomment-399573558

**Comment by cyChop** [comment]
Thanks for the pointers!
