### ISSUE TITLE
Support structs instead of map[string]interface{}

### ISSUE THREAD

**Issue by parkr** [nicksnyder/go-i18n#24]
Hey @nicksnyder!

Thanks for writing this great series of packages. We're looking into using them and we're running into a fairly large issue: when we call a `Tfunc`, it is automatically cast to a `map[string]interface{}` instead of being left alone. As a result, my struct doesn't resolve properties.

Thoughts?

**Comment by nicksnyder** [comment]
Yeah, Tfunc currently only accepts map[string]interface{} for data, [documented here](http://godoc.org/github.com/nicksnyder/go-i18n/i18n#TranslateFunc).

Thanks for the suggestion though, I am not sure why I never really considered allowing structs to pass through. I assume that the structs you are passing to TFunc are used elsewhere in your program and that is why you don't want to bother converting them to be maps?

As of right now these usages are supported:
```
T("You have {{.Count}} unread emails.", 2)
T("{{.Person}} has {{.Count}} unread emails", 2, map[string]interface{}{
    "Person": "Bob",
})
```

In both cases, the value for `{{.Count}}` is automatically provided to the template as a convenience.

The first case isn't really a problem on its own because internally we could still use a map.

For the second case, I am not sure what the best way to handle this is. I can think of a few options off the top of my head, none of which are particularly appealing:

1. Do runtime reflection to convert the struct to a map and then proceed to provide `{{.Count}}` as normal.
2. When a struct is passed, do not automatically try to provide `{{.Count}}`. This makes the behavior slightly different between using a struct and map.
3. Stop providing `{{.Count}}` as a convenience variable completely (backward incompatible change).

I think I will have to meditate on this. Do you have any thoughts?

**Comment by parkr** [comment]
What if you had a parent `TranslatableData` struct which was:

```go
type TranslationTmplData struct {
    Count int
    Data interface{}
}
```

then we could have something like

```go
T("You have {{.Count}} unread emails.", 2)
T("{{.Data.Person}} has {{.Count}} unread emails", 2, map[string]interface{}{
    "Person": "Bob",
})
T("{{.Data.Person}} has {{.Count}} unread emails", 2, struct{
        Person string
    }{
        Person: "Bob",
})
```

:question: 

Definitely not fully backwards-compatible, but would shiv struct support.

**Comment by nicksnyder** [comment]
Eh, I don't like the extra `.Data` required when referencing values in the templates. Seems unnecessarily complex.

I think I want to investigate the perf impact of #1 compared to #2

**Comment by parkr** [comment]
I don't have experience with runtime reflection, but I could probably help with (1) if you would like.

**Comment by nicksnyder** [comment]
I think the next step is to code up (1). It shouldn't be too hard, and we don't need to do it recursively. Only the top level needs to be a map. If you want to give it a shot, go for it.

**Comment by parkr** [comment]
What do you think about using something like https://github.com/fatih/structs ?

**Comment by nicksnyder** [comment]
There is no reason to add a dependency. Any general solution to this problem is going to be overkill because it will probably convert the struct to a map recursively (which we don't need).

My guess is that to do what we need will only require about 20 lines of code. Feel free to use that project  as inspiration and/or copy code (license permitting!).
