### ISSUE TITLE
Reseting err to nil after falling back on Other plural form

### ISSUE THREAD

**Issue by salihzain** [nicksnyder/go-i18n#241]
This package is awesome! Thanks for putting in all the efforts :) 

I noticed that on lines 161 - 169 inside `localizer.go`, the Localizer tries to fallback on the `Other` plural form if for example few isn't found. Given the code:
```
// Attempt to fallback to "Other" pluralization in case translations are incomplete.
if pluralForm != plural.Other {
	msg2, err3 := template.Execute(plural.Other, templateData, lc.Funcs)
	if err3 == nil {
		msg = msg2
	}
}
return msg, tag, err
``` 

I noticed that if err3 == nil, the msg is set to msg2 but err isn't set to nil. So I'm getting back an error even though the localizer has correctly fallen back to the Other form. I'm wondering, is this the intended use of the package?

**Comment by nicksnyder** [comment]
I wrote it this way intentionally, but I am open to feedback if this isn't intuitive. Right now go-i18n does its best to return a string, but if that string is grammatically wrong (because, for example, a translation is missing), then it will _also_ return an error.

**Comment by salihzain** [comment]
Makes total sense, thank you for the explanation @nicksnyder  👍

**Comment by decademoon** [comment]
If fallback is a feature of this library then it doesn't make sense that this function would return an error when it correctly resolved the message, even if that message was the fallback. It makes using this library a bit awkward unless every language file contains all messages - no missing translations are allowed, which isn't always achievable for every application.

Is it possible to use this library with partial translations and fallback to, say, English? I'm thinking either:

1. Never use `MustLocalize` since it will panic on fallback. Use `Localize` and ignore the error (!) or just check for an empty string.
2. When loading messages for each language, pre-populate any missing messages with the corresponding message from the fallback.

Thoughts?

**Comment by nicksnyder** [comment]
> If fallback is a feature of this library then it doesn't make sense that this function would return an error when it correctly resolved the message, even if that message was the fallback.

Sorry it doesn't make sense to you. An error is returned when the returned string breaks the user experience (most users expect to see the same language for everything in a single page, it is weird to mix languages). Needing to fall back is an error. The library gives you a string as best effort even when an error happens under the thinking that a string of the wrong language is better than the empty string (but it is still an error). 

> Use Localize and ignore the error (!) or just check for an empty string.

You can certainly do this.

> When loading messages for each language, pre-populate any missing messages with the corresponding message from the fallback.

Yes you could pre-process your language files in this way and that would be fine. Go-i18n is designed to be fast at runtime, so doesn't attempt to implement complex fallback logic.
