### ISSUE TITLE
Locale Precedence not working 

### ISSUE THREAD

**Issue by swap-patel** [nicksnyder/go-i18n#271]
We are using this library in one of our go project for localising the response messages. I am defining messages of different locale in different JSON/YAML files which are loaded at once during the app startup. Then deciding locale preference based on the inputs received in the request and expect Localiser to process it accordingly.
For instance, if I receive **vi-SG** in the request, the order of locale preference could be **_vi-SG -> vi -> en (default lang)_**. While passing this preference order to Localizer, it's checking for the value of requested MessageID in **vi-SG**. If it's not found, it directly checks in the default lang configured (en in this case) and returns the localised message (note that default locale file will always have the required messages). Based on the preference provided, it should have checked for **vi** and if the value is not found in this file as well, only then fallback to default locale.

**Comment by nicksnyder** [comment]
What you are observing here is the intended behavior. If you provide a translation file like vi-SG, go-i18n assumes that it contains all translations (and if not it falls back to the default language). This behavior ensures translation lookups are fast and also ensures a consistent user experience (otherwise it would be possible to see more than two languages on a single page). The fix to your problem is to ensure vi-SG is complete (copying in translations from vi if appropriate).
