### ISSUE TITLE
Suggestion/RFC: better/more efficient JSON structure

### ISSUE THREAD

**Issue by dalu** [nicksnyder/go-i18n#32]
Right now the JSON structure is ~
```json
[
  {
    "id": "id",
    "translation": "translation"
  },
  {
    "id": "id2",
    "translation": {
      "one": "{{.Count}} one",
      "other": "{{.Count}} other"
    }
  }
]
```

I like this package because it solves 2 problems in 1 swing.
When you write a modern web app/site you have 1 mobile version and 1 "desktop" version, ideally.
The source/input is json and could be used for mobile versions and the Go/package version could be used for desktop versions (because seo, server side rendered, yada yada).
Now when using it for mobile apps, using javascript, or a library like AngularJS you have to do a forEach, so you iterate over all datasets, check if id == the wanted id. On large translations with many datasets this could take a while and would need to be done once for each sought id.

A better or more efficient approach, imho, would be following structure

```json
{
  "id": {
    "translation": "translation"
  },
  "id2": {
    "translation": {
      "one": "{{.Count}} one",
      "other": "{{.Count}} other"
    }
  }
}
```

This would allow getting the translation by id instead of iterating over all datasets.
Example `var id = en_us.id;` or `var id2 = en_us.id2.one`

On the other hand this would mean restructuring this library and it probably a great amount of work.
But what about a command or option to transform the current structure into the proposed?
And thinking further, what about an option to concat translation files?
Something like

```json
{
  "de_de": {
    "id1": {
      "translation": "uebersetzung1"
    },
    "id2": {
      "one": "{{.Count}} eins",
      "translation": "uebersetzung2"
    }
  },
  "en_us": {
    "id1": {
      "translation": "translation1"
    },
    "id2": {
      "one": "{{.Count}} one",
      "translation": "translation2"
    }
  }
}
```

http://play.golang.org/p/Kx9k5-2NBd

**Comment by nicksnyder** [comment]
@dalu 

Yes, it would be inefficient to simply iterate over all translations for each lookup; don't do that :)

The file format wasn't designed to just be included directly on a page and accessed from javascript; it is just a data format to represent the translations. Even the go library processes this file a bit to store the translations at runtime for efficient lookups.

If you want to access translations from JavaScript it would make sense to write a program that transforms the data into a more desirable format (i.e. a map structure).

I think having one file per locale is easier to manage from a workflow perspective because languages get translated independently. Also, I don't think you would want all translations in one file for the web case anyway, because you wouldn't want to load all the translations for languages that the user isn't using (just load the one file of the user's current language).
