### ISSUE TITLE
error on fallback to non-default less specific language

### ISSUE THREAD

**Issue by le-yams** [nicksnyder/go-i18n#349]
## Description

go-i18n version: v2.4.1

When asking for a given language, if not defined it correctly fallback to a less specific language. But if the specific language is define but has not a given key it fails.  Thus, all non specific keys must be duplicated and redefined for the specific language.

Here is a test to reproduce the error:
```go
bundle := i18n.NewBundle(language.English)

fr := language.MustParse("fr")
frBE := language.MustParse("fr-BE")

bundle.MustAddMessages(fr, &i18n.Message{ID: "key1", Other: "fr key 1"})
bundle.MustAddMessages(fr, &i18n.Message{ID: "key2", Other: "fr key 2"})
bundle.MustAddMessages(frBE, &i18n.Message{ID: "key2", Other: "fr-BE specific key 2"})

localizerFrBE := i18n.NewLocalizer(bundle, "fr-BE")

key1 := localizerFrBE.MustLocalize(&i18n.LocalizeConfig{MessageID: "key1"})
key2 := localizerFrBE.MustLocalize(&i18n.LocalizeConfig{MessageID: "key2"})

if key1 != "fr key 1" {
  t.Error("key1 should 'be fr key 1'")
}
if key2 != "fr-BE specific key 2" {
  t.Error("key2 should 'be fr-BE specific key 2'")
}
```

## Expected behavior
The test should pass and the `key2` variable should have the value `fr-BE specific key 2`

## Actual behavior
I get the error message
> message "key1" not found in language "fr-BE"

Thanks in advance for your help.

Regards,
Yann

**Comment by nicksnyder** [comment]
> But if the specific language is define but has not a given key it fails. Thus, all non specific keys must be duplicated and redefined for the specific language.

You are correct that this is how the library behaves, and this was an intentional design decision. If you register a language, you need to provide all translations for that language. The reason for this design is that `golang.org/x/text/language.Matcher` is a relatively expensive object to create, so we really don't want to have to create it for every single call to `Localize` or for every single message id (which I think is what would need to happen to be able to support the behavior you want). Instead, the library expects users to provide complete translations files.

In particular for this case, `localizerFrBE := i18n.NewLocalizer(bundle, "fr-BE")` doesn't even indicate that `fr` is a valid fallback language, and in general it is not safe to assume that `xx` is a safe fallback for `xx-YY`.

That said, even in the case of `localizerFrBE := i18n.NewLocalizer(bundle, "fr-BE fr")`, the localizer will match on `fr-BE` since it has translations and will never fallback to `fr` for a single translation (unless there are no translations for `fr-BE` at all).

I understand why it would be nice to have this handled within the library, but in terms of overall complexity and performance I think it is best to just copy translations.

**Comment by le-yams** [comment]
> in general it is not safe to assume that xx is a safe fallback for xx-YY

I would argue that it is a very common usage (probably the main one ^^). Moreover this library already makes that assumption when the specific language doesn't exist at all. So it kind of fall between two stools, in one case you make that assumption but not in another case.

> The reason for this design is that golang.org/x/text/language.Matcher is a relatively expensive object to create, so we really don't want to have to create it for every single call to Localize or for every single message id (which I think is what would need to happen to be able to support the behavior you want). Instead, the library expects users to provide complete translations files.
> I understand why it would be nice to have this handled within the library, but in terms of overall complexity and performance I think it is best to just copy translations.

That makes perfect sense :). I'll try to dive in the code if I have some time and perhaps make a PR if I find a solution that might be interesting.
Thanks for your time.

Regards,
Yann
