### ISSUE TITLE
zero-other combination bug

### ISSUE THREAD

**Issue by toby3d** [nicksnyder/go-i18n#58]
Let's say I have two files as follows:
```
// en-us.json
[
    {
        "id": "sample_test",
        "translation": {
            "other": "{{.Type}} by {{.Owner}}",
            "zero": "Nobody here but us chickens!"
        }
    }
]
```
```
// ru-ru.json
[
    {
        "id": "sample_test",
        "translation": {
            "other": "{{.Type}} от {{.Owner}}",
            "zero": "Здесь никого, кроме нас, цыплят!"
        }
    }
]
```

After I get a merge files the following lines:
```
// en-us.all.json
[
    {
        "id": "sample_test",
        "translation": {
            "one": "",
            "other": "{{.Type}} by {{.Owner}}"
        }
    }
]
```
```
// ru-ru.all.json
[
    {
        "id": "sample_test",
        "translation": {
            "few": "",
            "many": "",
            "one": "",
            "other": "{{.Type}} от {{.Owner}}"
        }
    }
]
```

So... WTF?
I want to use the translation only in two cases:
- If the variable is equal to 0 - show "empty" translation (text only)
- If the variable is greater than 0 - show the value of a universal translation

I do not want to duplicate the line, for example, for a value of 1, this is an extra information trash and additional fixes.

**Comment by toby3d** [comment]
It's funny that in compiled **.untranslated.json** files I also get completely different results:
```
// en-us.untranslated.json
[
    {
        "id": "sample_test",
        "translation": {
            "one": "{{.Type}} by {{.Owner}}",
            "other": "{{.Type}} by {{.Owner}}"
        }
    }
]
```
```
// ru-ru.untranslated.json
[
    {
        "id": "sample_test",
        "translation": {
            "few": "{{.Type}} by {{.Owner}}",
            "many": "{{.Type}} by {{.Owner}}",
            "one": "{{.Type}} by {{.Owner}}",
            "other": "{{.Type}} от {{.Owner}}"
        }
    }
]
```

**Comment by nicksnyder** [comment]
There are a couple things you need to understand about pluralization in languages.

**1) zero != 0**

You can't assume that plural categories like zero, one, two map to specific numbers like 0, 1, 2. In some languages the "two" category might be used for any number that ends in the number 2 (e.g. 2, 12, 22, etc.). 

If you want to have special logic for specific numbers like 0, 1, 2, then you need to write code and have different translations for each of these cases.

```
// gross pseudocode
if x == 0 {
    t("no_apples")
} else {
    t("some_apples", x)
}
```

**2) Plural categories depend on the language**

English has two plural categories: one ("I have 1 apple") and other ("I have 0 apples", "I have 2 apples", etc.). There is no zero category in English because the pluralization for zero is not special.

Russian has four categories: few, many, one, other (and does not have a zero category). You need to provide a translation for all of the four categories unless you are ok with saying the equivalent of "I have 1 apples".

The goi18n tool understands which pluralizations belong to which languages, so it will drop useless pluralizations (e.g. zero in English, and zero in Russian) and add pluralizations that you need to translate (e.g. few, many, one, other in Russian).

The `.untranslated.json` file is what you send to translators to translate so it include all keys with either the known translation or the source English translation. Since Russian has a few category and English does not, it defaults to copying over the other source string from English. It is up to the translator to decide what translation make sense.

I hope this clarifies some things for you. From what I can tell, all of the behavior that you have observed is expected.
