### ISSUE TITLE
Support synonyms for id and translation

### ISSUE THREAD

**Issue by Noki** [nicksnyder/go-i18n#63]
Hi!

We started using go-i18n in one of our projects some time ago. Thank you for making our life easier!

Currently we are in the process of translating everything to several languages and started using an online service to coordinate the translations. We can export the translations from there in json format, and using them is as easy as replacing the name of the keys:

term => id
definition => translation

Is there any chance to handle term and definition as synonyms of id and translation? In that case we would be able to use the files directly without converting them at all.

Here is the format definition of the service we use: https://poeditor.com/localization/files/json

Best Regards
Tobias

**Comment by nicksnyder** [comment]
Thanks for taking the time to suggest this. poeditor looks like a cool service and I am kind surprised that their format is so similar.

I would rather not introduce complexity into go-i18n as a result of a specific service because then people will ask to support other services. If there were a standard JSON format, I would just support that (but there isn't to my knowledge).

I think the solution here (and for any other service) to either 
(1) write a script that marshals go-i18n's format to your desired format, or vice versa, or
(2) write code to read your own format and add the translations directly to the bundle with [AddTranslation](https://godoc.org/github.com/nicksnyder/go-i18n/i18n/bundle#Bundle.AddTranslation) at runtime.

If poeditor is/becomes **the** de facto tool for Go projects such that its format becomes the de facto standard, then I am open to revisiting this.

**Comment by Noki** [comment]
Ok. I already expected this answer. There are so many services that help with translations so I don't expect any of those to become a de facto standard any time soon. ;-)

We just came up with the following simple solution:

1. read the files exported from poeditor
2. replace the keys
3. pass the result to [ParseTranslationFileBytes](https://godoc.org/github.com/nicksnyder/go-i18n/i18n/bundle#Bundle.ParseTranslationFileBytes)

You should consider pointing out out the ideas of using AddTranslation or ParseTranslationFileBytes to import translations from different formats in the readme.

Best regards
Tobias
